### ISSUE TITLE
semantic-segmentation

### ISSUE THREAD

**Issue by kairos03** [kairos03/RODC#13]
http://blog.qure.ai/notes/semantic-segmentation-deep-learning-review

**Comment by mike2ox** [comment]
https://cs.stackexchange.com/questions/51387/what-is-the-difference-between-object-detection-semantic-segmentation-and-local

**Comment by kairos03** [comment]
https://github.com/handong1587/handong1587.github.io/blob/master/_posts/deep_learning/2015-10-09-segmentation.md

**Comment by mike2ox** [comment]
DAVIS 2017 challenge
https://arxiv.org/pdf/1704.00675.pdf

**Comment by mike2ox** [comment]
http://warmspringwinds.github.io/tensorflow/tf-slim/2017/01/23/fully-convolutional-networks-(fcns)-for-image-segmentation/

**Comment by kairos03** [comment]
#4
